
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: Language Cafe Orava
subtitle: ""
url: "https://jozef.chmelar.tech/LanguageCafeOrava/" # the base hostname & protocol for your site
# baseurl: "/the/subpath/of/your/site" # Set this value to "" if you want your site to be root
baseurl: "/LanguageCafeOrava"
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown

# Google analytics
ga_tracking_id: "UA-139370409-2"

# Category descriptions (for archive pages)
# descriptions:
#   - cat: jekyll
#     desc: "Posts describing Jekyll setup techniques."

#   - cat: dummy
#     desc: "Just some placeholder posts, lorem ipsum and the rest."
